Controllers/NguoiDungController.cs
using Facebook;
using ServiceStack.Text;
using ShopBon.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopBon.Controllers
{
    public class NguoiDungController : Controller
    { dbShopBonDataContext db = new dbShopBonDataContext();

        

        // GET: NguoiDung
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult DangKi()
        {
            return View("DangKi");
        }
        [HttpPost]
        public ActionResult DangKi(FormCollection collection,User kh )
        {
            var hoten = collection["HoTenKH"];
            var tendn = collection["TenDN"];
            var matkhau = collection["MatKhau"];
            var nhaplaimatkhau = collection["NhapLaiMatKhau"];
            var diachi = collection["DiaChi"];
            var email = collection["Email"];
            var dienthoai = collection["DienThoai"];
            var anhdaidien = collection["AnhDaiDien"];
            var ngaysinh = String.Format("{0:MM/dd/yyyy}", collection["NgaySinh"]);
            if (String.IsNullOrEmpty(hoten))
            {
                ViewData["Loi1"] = "Họ Tên Khách Hàng Không Được Để Trống";
            }
            else if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi2"] = "Phải nhập Tên Đăng Nhập";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi3"] = "Phải Nhập Mật Khẩu";
            }
            else if (String.IsNullOrEmpty(nhaplaimatkhau))
            {
                ViewData["Loi4"] = "Phải Nhập Lại Mật Khẩu";

            }
            else if (String.IsNullOrEmpty(diachi))
            {
                ViewData["Loi5"] = "Phải Nhập Địa Chỉ";

            }
            if (string.IsNullOrEmpty(email))
            {
                ViewData["Loi6"] = "Email Không Được Bỏ trống";
            }
             if (String.IsNullOrEmpty(dienthoai))
            {
                ViewData["Loi7"] = "Phải Nhập Điện Thoại";
            }

            
            else
            {
                kh.FullName = hoten;
                kh.UserName = tendn;
                kh.Password = matkhau;
                kh.Email = email;
                kh.Address = diachi;
                kh.Phone = dienthoai;   
                kh.Created_At = DateTime.Parse(ngaysinh);
                db.Users.InsertOnSubmit(kh);
                db.SubmitChanges();

                return RedirectToAction("DangNhap");                                                                                                                                                             
                
            }
            return this.DangKi();
        }
        [HttpGet]
        public ActionResult DangNhap()
        {
            return View("DangNhap");
        }

        [HttpPost]
        public ActionResult DangNhap(FormCollection collection)
        {
            var tendn = collection["TenDN"];
            var matkhau = collection["MatKhau"];
            if(String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Phải Nhập Tên Đăng Nhập";
            }
            else if(String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Phải nhập Mật Khẩu";
            }
            else
            {
                User kh = db.Users.SingleOrDefault(n => n.UserName == tendn && n.Password == matkhau);
                if (kh != null)
                {
                    //ViewBag.ThongBao = "Chúc Mừng Đăng Nhập Thành Công";
                    Session["UserName"] = kh;
                    return RedirectToAction("Index", "Site");
                }
                else
                    ViewBag.ThongBao = "Tên Đăng Nhập Hoặc Mật Khẩu Không Đúng";
            }
            return View();
        }
       
       
        
    }
}

Controllers/SiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopBon.Models;

using PagedList;
using PagedList.Mvc;
namespace ShopBon.Controllers
{
    public class SiteController : Controller
    {
        dbShopBonDataContext db = new dbShopBonDataContext();
        private List<Product> LayNHMoi(int count)
        {
            return db.Products.OrderByDescending(a => a.Created_At).Take(count).ToList();
        }
        // GET: Site
        public ActionResult Index(int ? page)
        {
            //int SoMauTin = db.Products.Count();
            //ViewBag.SoMauTin = SoMauTin;
            int pageSize = 6;
            int pageNum = (page ?? 1);
            var NHMoi = LayNHMoi(500);
           

            return View(NHMoi.ToPagedList(pageNum,pageSize));
        }
        public ActionResult ChuDe()
        {
            var ChuDe = from cd in db.Categories select cd;
            return PartialView(ChuDe);
        }
        public ActionResult DeTai()
        {
            var DeTai = from dt in db.Topics select dt;
            return PartialView(DeTai);
        }
        public ActionResult SanPhamTheoLoai(int id)
        {
            var SanPham = from sp in db.Products where sp.CatId == id select sp;

            return View(SanPham);
        }
        public ActionResult DeTaiMoi(string id)
        {
            var DeTai = from dt in db.Topics where dt.Slug == id select dt;  

            return View(DeTai);
        }
        public ActionResult Details(int id)
        {
            var SanPham = from sp in db.Products
                          where sp.Id == id
                          select sp;

            return View(SanPham.Single());
        }
        public ActionResult Menu()
        {
            User kh = (User)Session["UserName"];
            //var user = from us in db.Users select us;
            return PartialView(kh);

           
        }


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta charset="UTF-8">

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Public/css/all.min.css" rel="stylesheet" />
    <link href="~/Public/css/layout.css" rel="stylesheet" />

    @RenderSection("head", required: false)
</head>
<body>
    <div id="fb-root"></div>
        <script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v11.0&appId=3332707726956028&autoLogAppEvents=1" nonce="1zcbI6Vk"></script>
    <script>

        function statusChangeCallback(response) {  // Called with the results from FB.getLoginStatus().
            console.log('statusChangeCallback');
            console.log(response);                   // The current login status of the person.
            if (response.status === 'connected') {   // Logged into your webpage and Facebook.
                testAPI();
            } else {                                 // Not logged into your webpage or we are unable to tell.
                document.getElementById('status').innerHTML = 'Please log ' +
                    'into this webpage.';
            }
        }


        function checkLoginState() {               // Called when a person is finished with the Login Button.
            FB.getLoginStatus(function (response) {   // See the onlogin handler
                statusChangeCallback(response);
            });
        }


        window.fbAsyncInit = function () {
            FB.init({
                appId: '{3332707726956028',
                cookie: true,                     // Enable cookies to allow the server to access the session.
                xfbml: true,                     // Parse social plugins on this webpage.
                version: '{v11.0}'           // Use this Graph API version for this call.
            });


            FB.getLoginStatus(function (response) {   // Called after the JS SDK has been initialized.
                statusChangeCallback(response);        // Returns the login status.
            });
        };

        function testAPI() {                      // Testing Graph API after login.  See statusChangeCallback() for when this call is made.
            console.log('Welcome!  Fetching your information.... ');
            FB.api('/me', function (response) {
                console.log('Successful login for: ' + response.name);
                document.getElementById('status').innerHTML =
                    'Thanks for logging in, ' + response.name + '!';
            });
    
        }

    </script>
    <div id="status">
    </div>

    <!-- Load the JS SDK asynchronously -->
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js"></script>
    <section id="hearder" class="bg-primary">
        <div class="container">

            <div class="col-md-2 logo">
                <a href="@Url.Action("Index","Site")"><img src="~/Public/Images/logo/logoNH.jpg" class="img-circle" /></a>
            </div>
            <div style="margin-top:70px" class="col-md-6 ">

                <form class="navbar-form navbar-left">
                    <div class="form-group">
                        <input style="width:450px" type="text" class="form-control" placeholder="Nhập Từ KHóa Cần Tìm">
                    </div>
                    <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                </form>
            </div>
            <div style="margin-top:80px" class="col-md-2">
                <a style="width: 180px; height: 30px" class="btn btn-danger"><i class="fas fa-phone">Hotline:0932045603</i></a>
            </div>
            <div style="margin-top:80px" class="col-md-2">
                <a style="color:tomato"><i class="fas fa-shopping-cart"></i>@Html.Action("GioHangPartial", "GioHang")</a>
            </div>
        </div>

    </section>

    <section id="mainmenu" class="mainmenu">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Thông Tin Mới<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.Action("Detai", "Site")</li>

                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Các Loại Sản Phẩm <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.Action("ChuDe", "Site")</li>

                            </ul>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">Link</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Thành Viên @Html.Action("Menu", "Site") <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("DangKi","NguoiDung")">Đăng Ký Thành Viên</a></li>
                                <li><a href="@Url.Action("DangNhap","NguoiDung")">Đăng Nhập</a></li>
                                <li><a href="@Url.Action("Login","Admin")">Admin</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </section>
    <section id="maincontent">
    </section>
    <section id="footer">
    </section>
    <section id="copyright">
    </section>

    @RenderBody()


    <script src="~/Scripts/jquery-3.4.1.min.js"></script>

    <script src="~/Scripts/popper.mim.js"></script>

    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>


    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Public/css/all.min.css" rel="stylesheet" />
    <link href="~/Public/css/layout.css" rel="stylesheet" />
    <script src="~/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({ selector: 'textarea' });</script>
    <script>
        <a href="~/tinymce/js/tinymce/license.txt">~/tinymce/js/tinymce/license.txt</a>
    </script>
    @RenderSection("head", required: false)
</head>
<body>
    <section id="mainmenu" class="mainmenu">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-left">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Quản Lí<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Product","Admin")">Quản lí Sản Phẩm</a></li>
                                <li><a href="@Url.Action("DangNhap","NguoiDung")">Đăng Nhập</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </section>
    <section id="maincontent">
    </section>
    <section id="footer">
    </section>
    <section id="copyright">
    </section>

    @RenderBody()


    <script src="~/Scripts/jquery-3.4.1.min.js"></script>

    <script src="~/Scripts/popper.mim.js"></script>

    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>