Controllers/SiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopBon.Models;

using PagedList;
using PagedList.Mvc;
namespace ShopBon.Controllers
{
    public class SiteController : Controller
    {
        dbShopBonDataContext db = new dbShopBonDataContext();
        private List<Product> LayNHMoi(int count)
        {
            return db.Products.OrderByDescending(a => a.Created_At).Take(count).ToList();
        }
        // GET: Site
        public ActionResult Index(int ? page)
        {
            //int SoMauTin = db.Products.Count();
            //ViewBag.SoMauTin = SoMauTin;
            int pageSize = 6;
            int pageNum = (page ?? 1);
            var NHMoi = LayNHMoi(500);
           

            return View(NHMoi.ToPagedList(pageNum,pageSize));
        }
        public ActionResult ChuDe()
        {
            var ChuDe = from cd in db.Categories select cd;
            return PartialView(ChuDe);
        }
        public ActionResult DeTai()
        {
            var DeTai = from dt in db.Topics select dt;
            return PartialView(DeTai);
        }
        public ActionResult SanPhamTheoLoai(int id)
        {
            var SanPham = from sp in db.Products where sp.CatId == id select sp;

            return View(SanPham);
        }
        public ActionResult DeTaiMoi(string id)
        {
            var DeTai = from dt in db.Topics where dt.Slug == id select dt;  

            return View(DeTai);
        }
        public ActionResult Details(int id)
        {
            var SanPham = from sp in db.Products
                          where sp.Id == id
                          select sp;

            return View(SanPham.Single());
        }
        public ActionResult Menu()
        {
            User kh = (User)Session["UserName"];
            //var user = from us in db.Users select us;
            return PartialView(kh);

           
        }


    }
}

Views/Site/ChuDe.cshtml
@model IEnumerable<ShopBon.Models.Category>

    <div class="list-group">
        @foreach (var item in Model)
        {
       
            <a href="@Url.Action("SanPhamTheoLoai","Site",new {id = item.Id })" class="list-group-item">
                @item.Name
            </a>
        }
    </div>

Views/Site/DeTai.cshtml
@model IEnumerable<ShopBon.Models.Topic>
    <div class="list-group">
        @foreach (var item in Model)
        {
            <a href="@Url.Action("DeTaiMoi","Site",new {id = item.Slug })" class="list-group-item">
                @item.Name
            </a>
        }
    </div>

Views/Site/DeTaiMoi.cshtml
@model IEnumerable<ShopBon.Models.Topic>
@{
    ViewBag.Title = "DeTaiMoi";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h3 style="text-align:center; color:red">Thông Tin</h3>
<div class="row">
    @foreach(var item in Model)
    {
        <a href="@Url.Action("Details","Site",new {id =item.Status })"></a>
    }
</div>

Views/Site/Details.cshtml
    <style type="text/css">
        #datmua a{
            clear:both; background-color:red;
            color:white;width:120px;height:35px;
            display:block;float:right;text-align:center;
            padding-top:10px;text-decoration:none;font-weight:bold;
        }
        #datmua a:hover{
            background-color:gray;
            color:red;
        }
    </style>
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Thông Tin Chi Tiết Sản Phẩm</h2>
<div>

 
        <div style="width:40%;float:left;border-left:dotted:1px;border-color:azure">
            <img src="~/Public/Images/@Model.Img" width="100%" />
        </div>
        <div style="width:60%;float:left;padding:10px">
            <h4 style="font-weight:bold;color:red">Tên Sách @Model.Name</h4>
            <p style="text-align:justify"><span style="font-weight:bold">Mô Tả</span>@Model.Detail</p>
            <p style="font-weight:bold">Giá Bán:<span style="color:red;font-size:16pt">@Model.PriceBuy</span></p>

          
        </div>
        <div id="datmua">
            <a href="@Url.Action("ThemGioHang","GioHang",new { @iMaSanPham = Model.Id, @strURL = Request.Url.ToString()  })" >Đặt Mua</a>
        </div>
    </div>

Views/Site/Index.cshtml
@using ShopBon.Models
@using PagedList.Mvc;
@model PagedList.PagedList<Product>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<div class="row">
    @foreach (var product in Model)
    {
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <a href="@Url.Action("Details","Site",new {id = product.Id})">
                    <img alt="@product.Name" src="~/Public/Images/@product.Img" width="200" />
                </a>
                <div>
                    <br />
                    <h4 style="text-align:center">
                        @product.Name
                    </h4>
                    <p></p>

                </div>
                <div class="ratings">
                    <p class="pull-right">15 review</p>
                    <p>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                    </p>
                </div>
            </div>
        </div>

    }
    
</div>
Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount;
<div class="MenuTrang">
    @Html.PagedListPager(Model,page => Url.Action("Index",new { page = page }))
</div>
<style>
    .MenuTrang li{
        display:inline;
    }
</style>

Views/Site/Menu.cshtml
@using ShopBon.Models
@{
    User kh = (User)Session["UserName"];
}

Views/Site/SanPhamTheoLoai.cshtml
@model IEnumerable<ShopBon.Models.Product>

@{
    ViewBag.Title = "SanPhamTheoLoai";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h3 style="text-align:center;color:red">Sản Phẩm Theo Chủ Đề</h3>
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <a href="@Url.Action("Details","Site",new {id = item.Id})">
                    <img alt="@item.Name" src="~/Public/Images/@item.Img" width="200" />
                </a>
                <div>
                    <br />
                    <h4 style="text-align:center">
                        @item.Name
                    </h4>
                    <p></p>
                </div>
                <div class="ratings">
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                </div>
            </div>
        </div>
    }
</div>